// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSYJsuzkBIH0_SJFr9u7WtfmzW0jCXIRQ',
    appId: '1:237161310344:web:34baacdadc699f5ced173d',
    messagingSenderId: '237161310344',
    projectId: 'task-manager-cedab',
    authDomain: 'task-manager-cedab.firebaseapp.com',
    storageBucket: 'task-manager-cedab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtb1IOy8W7gL-0A5gwSD16aZs9dckDwew',
    appId: '1:237161310344:android:2e439e137328384eed173d',
    messagingSenderId: '237161310344',
    projectId: 'task-manager-cedab',
    storageBucket: 'task-manager-cedab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWjw-zeVWz02FFlCh4YtYv1TOwU2Vygkc',
    appId: '1:237161310344:ios:f7cebadf842fdbe7ed173d',
    messagingSenderId: '237161310344',
    projectId: 'task-manager-cedab',
    storageBucket: 'task-manager-cedab.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWjw-zeVWz02FFlCh4YtYv1TOwU2Vygkc',
    appId: '1:237161310344:ios:f7cebadf842fdbe7ed173d',
    messagingSenderId: '237161310344',
    projectId: 'task-manager-cedab',
    storageBucket: 'task-manager-cedab.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSYJsuzkBIH0_SJFr9u7WtfmzW0jCXIRQ',
    appId: '1:237161310344:web:1ef2a45fe104ea1ced173d',
    messagingSenderId: '237161310344',
    projectId: 'task-manager-cedab',
    authDomain: 'task-manager-cedab.firebaseapp.com',
    storageBucket: 'task-manager-cedab.appspot.com',
  );
}
